[window]
padding = { x = 12, y = 12 }
dynamic_padding = true
decorations = "None"
startup_mode = "Windowed"
opacity = 0.95
[scrolling]
history = 10000
multiplier = 3
[font]
size = 12.0
[colors.primary]
background = "#242424"
foreground = "#DEDEDE"
[colors.cursor]
text = "#242424"
cursor = "#DEDEDE"
[colors.selection]
text = "#FFFFFF"
background = "#7E7E7E"
[colors.normal]
black = "#242424"
red = "#E06C75"
green = "#98C379"
yellow = "#E5C07B"
blue = "#61AFEF"
magenta = "#C678DD"
cyan = "#56B6C2"
white = "#DEDEDE"
[colors.bright]
black = "#71797E"
red = "#E06C75"
green = "#98C379"
yellow = "#E5C07B"
blue = "#61AFEF"
magenta = "#C678DD"
cyan = "#56B6C2"
white = "#FFFFFF"
[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750
thickness = 0.15
[mouse]
hide_when_typing = true
[bell]
animation = "EaseOutExpo"
duration = 0
color = "#FFFFFF"

